baseURL = "https://qseco.fr/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "terminal"

[params]
  themeColor = "green"
  fullWidthTheme = false
  centerTheme = true
  showLanguageSelector = false


[languages]
  [languages.en]
    languageName = "English"
    title = "QSECO.FR"
    copyright = "QSECO.FR Consulting"

    [languages.en.params.logo]
      logoText = "QSECO.FR"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "services"
        name = "001-services"
        url = "/services"
        title = "Services"

      [[languages.en.menu.main]]
        identifier = "002-projects"
        name = "002-projects"
        url = "/projects"
        title = "Projects"

      [[languages.en.menu.main]]
        identifier = "003-blog"
        name = "003-blog"
        url = "/blog"
        title = "Blog"

      [[languages.en.menu.main]]
        identifier = "004-contact"
        name = "004-contact"
        url = "/contact"
        title = "Contact"
