baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "terminal"

[params]
  themeColor = "green"
  fullWidthTheme = false
  centerTheme = true
  showLanguageSelector = false


[languages]
  [languages.en]
    languageName = "English"
    title = "QSECO.FR"
    [languages.en.params.logo]
      logoText = "QSECO.FR"
