baseURL = "https://qseco.fr/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "terminal"

[params]
  themeColor = "green"
  fullWidthTheme = false
  centerTheme = true
  showLanguageSelector = false


[languages]
  [languages.en]
    languageName = "English"
    title = "QSECO.FR"
    copyright = "QSECO.FR Consulting"

    [languages.en.params.logo]
      logoText = "QSECO.FR"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "services"
        name = "Services"
        url = "/services"
        weight = 100

      [[languages.en.menu.main]]
        identifier = "002-projects"
        name = "Projects"
        url = "/projects"
        weight = 200

      [[languages.en.menu.main]]
        identifier = "003-blog"
        name = "Blog"
        url = "/blog"
        weight = 300

      [[languages.en.menu.main]]
        identifier = "004-contact"
        name = "Contact"
        url = "/contact"
        weight = 400
